name: ws_chat_fcm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  web_socket_channel: ^3.0.1
  firebase_messaging: ^15.1.6

flutter:
  uses-material-design: true
